services:
  - type: web
    name: studentbiometric-backend
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /api/users
    envVars:
      - key: CORS_ALLOWED_ORIGINS
        value: https://bobb-35.github.io
